package Resources;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class RequestsController {

	// Event Listener on Button.onAction
	@FXML
	public void cancel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void accept(ActionEvent event) {
		// TODO Autogenerated
	}
}
